allowBuilds:
  '@carbon/icon-helpers': false
  '@carbon/icons': false
  'msgpackr-extract': false
  'unrs-resolver': false

catalog:
  'react': 19.2.3
  'react-native-builder-bob': 0.41.0

engineStrict: true

nodeLinker: hoisted

packages:
  - 'examples/*'
  - 'package'
  - 'package-builder'
