name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      packages: write # For publishing to the GitHub Packages
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Use PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11
          cache: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Code check
        run: npm run code-check
      - name: Build Package
        run: |
          npm run package-builder bob
      - name: UWS Mod
        run: |
          npm run package-builder uws-mod
      - name: Release to NPM registry
        run: |
          node ./scripts/release-npm.mjs
      - name: Release to GitHub Packages
        run: |
          node ./scripts/release-github.mjs
